services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TZ: ${TZ}
    depends_on:
      - redis
    volumes:
      - .:/var/www/html:cached
      - php_socket:/var/run/php

  nginx:
    image: nginx:1.24-alpine3.17
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/var/www/html/public:ro
      - php_socket:/var/run/php
    ports:
      - '${APP_EXT_PORT}:80'
  
  redis:
    image: 'redis:alpine'
    logging:
      options:
        max-size: 50m
    restart: always
    volumes:
      - redis:/data
    
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq/

  php-messenger:
    build:
      context: .
      dockerfile: docker/php-messenger/Dockerfile
      args:
        TZ: ${TZ}
    logging:
      options:
        max-size: 50m
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/var/www/html:cached

volumes:
  redis: ~
  php_socket: ~
  rabbitmq: ~