services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        TZ: ${TZ}
    volumes:
      - .:/var/www/html:cached
      - php_socket:/var/run/php

  nginx:
    image: nginx:1.24-alpine3.17
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public/:/var/www/html/public:ro
      - php_socket:/var/run/php
    ports:
      - '${APP_EXT_PORT}:80'

volumes:
  lms_db: ~
  php_socket: ~